In [ ]:
import tensorflow as tf

In [12]:
xy = tf.Variable([[2., 2.]])
with tf.GradientTape(persistent=True) as tape2:
    tape2.watch(xy)
    with tf.GradientTape() as tape:
        tape.watch(xy)
        f = 3 * (xy[:, 0] * xy[:, 1]) ** 2 + xy[:, 1] ** 2
    df = tape.gradient(f, xy)
    print(df)

d2f = tape2.gradient(df, xy)
print(d2f)
d2f_dx2 = d2f[:,0]
d2f_dy2 = d2f[:,1]
del tape2

print(d2f_dx2, d2f_dy2)

tf.Tensor([[48. 52.]], shape=(1, 2), dtype=float32)
tf.Tensor([[72. 74.]], shape=(1, 2), dtype=float32)
tf.Tensor([72.], shape=(1,), dtype=float32) tf.Tensor([74.], shape=(1,), dtype=float32)


In [3]:
xy = tf.Variable([[2., 2.]])
with tf.GradientTape(persistent=True) as tape2:
    tape2.watch(xy)
    with tf.GradientTape() as tape:
        tape.watch(xy)
        f = 3 * (xy[:, 0] * xy[:, 1]) ** 2 + xy[:, 1] ** 2
    df = tape.gradient(f, xy)
    del tape
    df_dx = df[..., 0]
    df_dy = df[..., 1]
    print(df_dx, df_dy)

d2f_dx = tape2.gradient(df_dx, xy)
d2f_dy = tape2.gradient(df_dy, xy)
print(d2f_dx, d2f_dy)
del tape2

tf.Tensor([48.], shape=(1,), dtype=float32) tf.Tensor([52.], shape=(1,), dtype=float32)
tf.Tensor([[24. 48.]], shape=(1, 2), dtype=float32) tf.Tensor([[48. 26.]], shape=(1, 2), dtype=float32)


In [3]:
xy = tf.Variable([[2., 2.]])
with tf.GradientTape(persistent=True) as tape:
    tape.watch(xy)
    f = 3 * (xy[:, 0] * xy[:, 1]) ** 2 + xy[:, 1] ** 2
    df = tape.gradient(f, xy)
    print(df)
    d2f = tape.gradient(df, xy)
    print(d2f)
    d2f_dx2 = d2f[:,0]
    d2f_dy2 = d2f[:,1]
del tape

print(d2f_dx2, d2f_dy2)

tf.Tensor([[48. 52.]], shape=(1, 2), dtype=float32)
tf.Tensor([[72. 74.]], shape=(1, 2), dtype=float32)
tf.Tensor([72.], shape=(1,), dtype=float32) tf.Tensor([74.], shape=(1,), dtype=float32)
